// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01.08.2024, 01:03:51
const configMerger = require("C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/plugins/**/*.{js,ts,mjs}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/composables/**/*.{js,ts,mjs}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/utils/**/*.{js,ts,mjs}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Switty/Documents/GitHub/RobinW-Langing-Nuxt-Learn/app.config.{js,ts,mjs}"] }));

module.exports = config
